# Generated by Django 3.0.2 on 2020-07-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
